apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: rohitdocker1996/kubernetes
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis