version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  django:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: rohitdocker1996/chatbot
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: rohitdocker1996/chatbot
    command: celery -A chatbot worker -l info
    depends_on:
      - redis
      - django