apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: static-volume
              mountPath: /static
      volumes:
        - name: nginx-config
          hostPath:
            path: /mnt/chatbots/chabotkube/nginx/nginx.conf
            type: File
        - name: static-volume
          hostPath:
            path: /mnt/chatbots/chabotkube/static
